### PR TITLE
fixing CoreExceptions in PropertyTester

### PR DESCRIPTION
**Pull request by puraner**
attempt to fix issue #325

### CODE REVIEW

**Comment by michalanglart** [comment]
I'll have a look at that tomorrow once I try it applying this patch on my machine. At first sight however it looks like this change would brake integration with PyDev. Once PyDev is installed it replaces the objects shown in package explorer with own wrappers so that instanceof test does not pass and objects needs to be adapted. All those <adapts> were added to fix this problem.

**Comment by michalanglart** [comment]
I've just checked it and as I feared your patch is braking PyDev integration. In order to reproduce:

- create new PyDev project
- add Robot nature to that project
- add Robot files to it

After that PyDev would replace objects displayed in `Project Explorer` view with own implementations: e.g. instead of `org.eclipse.core.resources.IFile` there is `org.python.pydev.navigator.elements.PythonFile` displayed and the latter do not implement `IFile` interface however it may be adapted to it. With your patch applied without `<adapts>` the menu options from `Robot Framework` are disabled.

However I was able to fix that so with next release there will be no exceptions logged under 2019-06.

Thank you!

**Comment by puraner** [comment]
Thats really good news! Thank you! Just for planning, when do you estimate the next release?

**Comment by michalanglart** [comment]
There are few things now implemented which make it worthy to prepare a new release soon. I think we will try to do it before August ends.

**Comment by puraner** [comment]
We would need a fixed version until next week :/ So would it be possible that you push your changes so we can build our own version?

**Comment by michalanglart** [comment]
Here's the patch you can use:
[gh_325.txt](https://github.com/nokia/RED/files/3500689/gh_325.txt)

I don't want to push the changes now since this could add some problems between our GitHub repo and internal Gerrit repo and further it may disturb our release procedure.

**Comment by puraner** [comment]
Thanks a lot!

**Pull request closed without merging**
